export const HSK1 = [
  { id: 1, english: "I", hanzi: "我", pinyin: "wǒ" },
  { id: 2, english: "you (singular)", hanzi: "你", pinyin: "nǐ" },
  { id: 3, english: "him/her", hanzi: "他/她", pinyin: "tā" },
  { id: 4, english: "we", hanzi: "我们", pinyin: "wǒmen" },
  { id: 5, english: "you (plural)", hanzi: "你们", pinyin: "nǐmen" },
  { id: 6, english: "they", hanzi: "他们/她们", pinyin: "tāmen" },
  { id: 7, english: "want", hanzi: "要", pinyin: "yào" },
  { id: 8, english: "would like", hanzi: "想", pinyin: "xiǎng" },
  { id: 9, english: "to go", hanzi: "去", pinyin: "qù" },
  { id: 10, english: "to eat", hanzi: "吃", pinyin: "chī" },
  { id: 11, english: "to drink", hanzi: "喝", pinyin: "hē" },
  { id: 12, english: "to order", hanzi: "点", pinyin: "diǎn" },
  { id: 13, english: "to make", hanzi: "做", pinyin: "zuò" },
  { id: 14, english: "to use", hanzi: "用", pinyin: "yòng" },
  { id: 15, english: "today", hanzi: "今天", pinyin: "jīntiān" },
  { id: 16, english: "tomorrow", hanzi: "明天", pinyin: "míngtiān" },
  { id: 17, english: "yesterday", hanzi: "昨天", pinyin: "zuótiān" },
  { id: 18, english: "afternoon", hanzi: "下午", pinyin: "xiàwǔ" },
  { id: 19, english: "morning", hanzi: "上午", pinyin: "shàngwǔ" },
  { id: 20, english: "this year", hanzi: "今年", pinyin: "jīnnián" },
  { id: 21, english: "next year", hanzi: "明年", pinyin: "míngnián" },
  { id: 22, english: "last year", hanzi: "去年", pinyin: "qùnián" },
  { id: 23, english: "computer", hanzi: "电脑", pinyin: "diànnǎo" },
  {
    id: 24,
    english: "one computer",
    hanzi: "一台电脑",
    pinyin: "yī tái diànnǎo",
  },
  { id: 25, english: "laptop", hanzi: "手提电脑", pinyin: "shǒutí diànnǎo" },
  { id: 26, english: "handbag", hanzi: "手提包", pinyin: "shǒutíbāo" },
  {
    id: 27,
    english: "one handbag",
    hanzi: "一个手提包",
    pinyin: "yī gè shǒutíbāo",
  },
  { id: 28, english: "fried noodles", hanzi: "炒面", pinyin: "chǎomiàn" },
  { id: 29, english: "fried rice", hanzi: "炒饭", pinyin: "chǎofàn" },
  {
    id: 30,
    english: "pockmarked old woman's tofu (mapo tofu)",
    hanzi: "麻婆豆腐",
    pinyin: "mápó dòufu",
  },
  {
    id: 31,
    english: "special fried rice",
    hanzi: "扬州炒饭",
    pinyin: "yángzhōu chǎofàn",
  },
  {
    id: 32,
    english: "sweet and sour pork",
    hanzi: "咕噜肉",
    pinyin: "gūlū ròu",
  },
  { id: 33, english: "bread", hanzi: "面包", pinyin: "miànbāo" },
  { id: 34, english: "roast duck", hanzi: "烤鸭", pinyin: "kǎoyā" },
  { id: 35, english: "steamed buns", hanzi: "包子", pinyin: "bāozi" },
  {
    id: 36,
    english: "pork steamed buns",
    hanzi: "猪肉包子",
    pinyin: "zhūròu bāozi",
  },
  {
    id: 37,
    english: "vegetable steamed buns",
    hanzi: "菜包子",
    pinyin: "cài bāozi",
  },
  {
    id: 38,
    english: "big white leaf (bok choy)",
    hanzi: "大白菜",
    pinyin: "dà báicài",
  },
  { id: 39, english: "tea", hanzi: "茶", pinyin: "chá" },
  { id: 40, english: "coffee", hanzi: "咖啡", pinyin: "kāfēi" },
  {
    id: 41,
    english: "black dragon tea (oolong)",
    hanzi: "乌龙茶",
    pinyin: "wūlóng chá",
  },
  { id: 42, english: "jasmine tea", hanzi: "茉莉花茶", pinyin: "mòlìhuā chá" },
  { id: 43, english: "water", hanzi: "水", pinyin: "shuǐ" },
  { id: 44, english: "Beijing", hanzi: "北京", pinyin: "Běijīng" },
  { id: 45, english: "Guangzhou", hanzi: "广州", pinyin: "Guǎngzhōu" },
  { id: 46, english: "Shanghai", hanzi: "上海", pinyin: "Shànghǎi" },
  {
    id: 47,
    english: "Tiananmen Square",
    hanzi: "天安门广场",
    pinyin: "Tiān'ānmén Guǎngchǎng",
  },
  { id: 48, english: "China", hanzi: "中国", pinyin: "Zhōngguó" },
  { id: 49, english: "Chinatown", hanzi: "唐人街", pinyin: "Tángrénjiē" },
  { id: 50, english: "England", hanzi: "英国", pinyin: "Yīngguó" },
  { id: 51, english: "Chinese", hanzi: "中文", pinyin: "Zhōngwén" },
  { id: 52, english: "English", hanzi: "英文", pinyin: "Yīngwén" },
  { id: 53, english: "mother", hanzi: "妈妈", pinyin: "māma" },
  { id: 54, english: "father", hanzi: "爸爸", pinyin: "bàba" },
  { id: 55, english: "one (unit)", hanzi: "一个", pinyin: "yī gè" },
  { id: 56, english: "a couple (unit)", hanzi: "两个", pinyin: "liǎng gè" },
  { id: 57, english: "can (allowed)", hanzi: "可以", pinyin: "kěyǐ" },
  { id: 58, english: "can (know how to)", hanzi: "会", pinyin: "huì" },
  { id: 59, english: "can (physically able)", hanzi: "能", pinyin: "néng" },
  { id: 60, english: "car", hanzi: "车", pinyin: "chē" },
  { id: 61, english: "to drive", hanzi: "开车", pinyin: "kāi chē" },
  { id: 62, english: "have", hanzi: "有", pinyin: "yǒu" },
  { id: 63, english: "don’t have", hanzi: "没有", pinyin: "méiyǒu" },
  { id: 64, english: "what", hanzi: "什么", pinyin: "shénme" },
  { id: 65, english: "question particle", hanzi: "吗", pinyin: "ma" },
  { id: 66, english: "plural suffix", hanzi: "们", pinyin: "men" },
  { id: 67, english: "please may I", hanzi: "请", pinyin: "qǐng" },
  { id: 68, english: "ask", hanzi: "问", pinyin: "wèn" },
  { id: 69, english: "questions", hanzi: "问题", pinyin: "wèntí" },
  { id: 70, english: "and", hanzi: "和", pinyin: "hé" },
  { id: 71, english: "but", hanzi: "但是", pinyin: "dànshì" },
  { id: 72, english: "dish", hanzi: "菜", pinyin: "cài" },
  { id: 73, english: "no / not", hanzi: "不", pinyin: "bù" },
];
