export const HSK1 = [
  { id: 1, english: "love", hanzi: "爱", pinyin: "ài" },
  { id: 2, english: "eight", hanzi: "八", pinyin: "bā" },
  { id: 3, english: "father", hanzi: "爸爸", pinyin: "bà ba" },
  { id: 4, english: "cup; glass", hanzi: "杯子", pinyin: "bēi zi" },
  { id: 5, english: "Beijing", hanzi: "北京", pinyin: "běi jīng" },
  { id: 6, english: "book", hanzi: "本", pinyin: "běn" },
  { id: 7, english: "you're welcome", hanzi: "不客气", pinyin: "bú kè qi" },
  { id: 8, english: "no; not", hanzi: "不", pinyin: "bù" },
  { id: 9, english: "dish; vegetables; cuisine", hanzi: "菜", pinyin: "cài" },
  { id: 10, english: "tea", hanzi: "茶", pinyin: "chá" },
  { id: 11, english: "to eat", hanzi: "吃", pinyin: "chī" },
  { id: 12, english: "taxi", hanzi: "出租车", pinyin: "chū zū chē" },
  {
    id: 13,
    english: "to make a phone call",
    hanzi: "打电话",
    pinyin: "dǎ diàn huà",
  },
  { id: 14, english: "big; large", hanzi: "大", pinyin: "dà" },
  { id: 15, english: "of; structural particle", hanzi: "的", pinyin: "de" },
  { id: 16, english: "a little; dot", hanzi: "点", pinyin: "diǎn" },
  { id: 17, english: "computer", hanzi: "电脑", pinyin: "diàn nǎo" },
  { id: 18, english: "television", hanzi: "电视", pinyin: "diàn shì" },
  { id: 19, english: "movie; film", hanzi: "电影", pinyin: "diàn yǐng" },
  { id: 20, english: "thing; stuff", hanzi: "东西", pinyin: "dōng xi" },
  { id: 21, english: "all; both", hanzi: "都", pinyin: "dōu" },
  { id: 22, english: "to read", hanzi: "读", pinyin: "dú" },
  { id: 23, english: "sorry", hanzi: "对不起", pinyin: "duì bu qǐ" },
  { id: 24, english: "many; much", hanzi: "多", pinyin: "duō" },
  { id: 25, english: "how many; how much", hanzi: "多少", pinyin: "duō shǎo" },
  { id: 26, english: "son", hanzi: "儿子", pinyin: "ér zi" },
  { id: 27, english: "two; 2", hanzi: "二", pinyin: "èr" },
  { id: 28, english: "restaurant; hotel", hanzi: "饭店", pinyin: "fàn diàn" },
  { id: 29, english: "airplane", hanzi: "飞机", pinyin: "fēi jī" },
  { id: 30, english: "minute", hanzi: "分钟", pinyin: "fēn zhōng" },
  { id: 31, english: "happy; glad", hanzi: "高兴", pinyin: "gāo xìng" },
  { id: 32, english: "measure word", hanzi: "个", pinyin: "gè" },
  { id: 33, english: "work; job", hanzi: "工作", pinyin: "gōng zuò" },
  { id: 34, english: "dog", hanzi: "狗", pinyin: "gǒu" },
  { id: 35, english: "Chinese language", hanzi: "汉语", pinyin: "hàn yǔ" },
  { id: 36, english: "good; well", hanzi: "好", pinyin: "hǎo" },
  { id: 37, english: "date; number", hanzi: "号", pinyin: "hào" },
  { id: 38, english: "to drink", hanzi: "喝", pinyin: "hē" },
  { id: 39, english: "and; with", hanzi: "和", pinyin: "hé" },
  { id: 40, english: "very", hanzi: "很", pinyin: "hěn" },
  { id: 41, english: "back; behind", hanzi: "后面", pinyin: "hòu miàn" },
  { id: 42, english: "to return", hanzi: "回", pinyin: "huí" },
  { id: 43, english: "can; to be able to", hanzi: "会", pinyin: "huì" },
  { id: 44, english: "how many; several", hanzi: "几", pinyin: "jǐ" },
  { id: 45, english: "home; family", hanzi: "家", pinyin: "jiā" },
  { id: 46, english: "to be called", hanzi: "叫", pinyin: "jiào" },
  { id: 47, english: "today", hanzi: "今天", pinyin: "jīn tiān" },
  { id: 48, english: "nine; 9", hanzi: "九", pinyin: "jiǔ" },
  { id: 49, english: "to open; to start", hanzi: "开", pinyin: "kāi" },
  { id: 50, english: "to look; to watch", hanzi: "看", pinyin: "kàn" },
  { id: 51, english: "to see", hanzi: "看见", pinyin: "kàn jiàn" },
  { id: 52, english: "piece; lump; chunk", hanzi: "块", pinyin: "kuài" },
  { id: 53, english: "come", hanzi: "来", pinyin: "lái" },
  { id: 54, english: "teacher", hanzi: "老师", pinyin: "lǎo shī" },
  {
    id: 55,
    english: "(particle for completed action)",
    hanzi: "了",
    pinyin: "le",
  },
  { id: 56, english: "cold", hanzi: "冷", pinyin: "lěng" },
  { id: 57, english: "in; inside", hanzi: "里", pinyin: "lǐ" },
  { id: 58, english: "six", hanzi: "六", pinyin: "liù" },
  { id: 59, english: "(question particle)", hanzi: "吗", pinyin: "ma" },
  { id: 60, english: "mother", hanzi: "妈妈", pinyin: "mā ma" },
  { id: 61, english: "to buy", hanzi: "买", pinyin: "mǎi" },
  { id: 62, english: "cat", hanzi: "猫", pinyin: "māo" },
  {
    id: 63,
    english: "it's okay; never mind",
    hanzi: "没关系",
    pinyin: "méi guān xi",
  },
  { id: 64, english: "not have", hanzi: "没有", pinyin: "méi yǒu" },
  { id: 65, english: "rice", hanzi: "米饭", pinyin: "mǐ fàn" },
  { id: 66, english: "name", hanzi: "名字", pinyin: "míng zi" },
  { id: 67, english: "tomorrow", hanzi: "明天", pinyin: "míng tiān" },
  { id: 68, english: "which", hanzi: "哪", pinyin: "nǎ" },
  { id: 69, english: "where", hanzi: "哪儿", pinyin: "nǎ er" },
  { id: 70, english: "that", hanzi: "那", pinyin: "nà" },
  { id: 71, english: "(question particle)", hanzi: "呢", pinyin: "ne" },
  { id: 72, english: "can; to be able to", hanzi: "能", pinyin: "néng" },
  { id: 73, english: "you", hanzi: "你", pinyin: "nǐ" },
  { id: 74, english: "year", hanzi: "年", pinyin: "nián" },
  { id: 75, english: "daughter", hanzi: "女儿", pinyin: "nǚ ér" },
  { id: 76, english: "friend", hanzi: "朋友", pinyin: "péng you" },
  { id: 77, english: "pretty", hanzi: "漂亮", pinyin: "piào liang" },
  { id: 78, english: "apple", hanzi: "苹果", pinyin: "píng guǒ" },
  { id: 79, english: "seven", hanzi: "七", pinyin: "qī" },
  { id: 80, english: "in front", hanzi: "前面", pinyin: "qián miàn" },
  { id: 81, english: "money", hanzi: "钱", pinyin: "qián" },
  { id: 82, english: "please", hanzi: "请", pinyin: "qǐng" },
  { id: 83, english: "to go", hanzi: "去", pinyin: "qù" },
  { id: 84, english: "hot", hanzi: "热", pinyin: "rè" },
  { id: 85, english: "person", hanzi: "人", pinyin: "rén" },
  { id: 86, english: "to know (someone)", hanzi: "认识", pinyin: "rèn shi" },
  { id: 87, english: "three", hanzi: "三", pinyin: "sān" },
  { id: 88, english: "shop", hanzi: "商店", pinyin: "shāng diàn" },
  { id: 89, english: "above; up", hanzi: "上", pinyin: "shàng" },
  { id: 90, english: "morning", hanzi: "上午", pinyin: "shàng wǔ" },
  { id: 91, english: "few; little", hanzi: "少", pinyin: "shǎo" },
  { id: 92, english: "who", hanzi: "谁", pinyin: "shéi" },
  { id: 93, english: "what", hanzi: "什么", pinyin: "shén me" },
  { id: 94, english: "ten", hanzi: "十", pinyin: "shí" },
  { id: 95, english: "time; moment", hanzi: "时候", pinyin: "shí hou" },
  { id: 96, english: "to be", hanzi: "是", pinyin: "shì" },
  { id: 97, english: "book", hanzi: "书", pinyin: "shū" },
  { id: 98, english: "water", hanzi: "水", pinyin: "shuǐ" },
  { id: 99, english: "fruit", hanzi: "水果", pinyin: "shuǐ guǒ" },
  { id: 100, english: "to sleep", hanzi: "睡觉", pinyin: "shuì jiào" },
  { id: 101, english: "to speak", hanzi: "说", pinyin: "shuō" },
  { id: 102, english: "four", hanzi: "四", pinyin: "sì" },
  { id: 103, english: "age; years old", hanzi: "岁", pinyin: "suì" },
  { id: 104, english: "he / him", hanzi: "他", pinyin: "tā" },
  { id: 105, english: "she / her", hanzi: "她", pinyin: "tā" },
  { id: 106, english: "too; excessively", hanzi: "太", pinyin: "tài" },
  { id: 107, english: "weather", hanzi: "天气", pinyin: "tiān qì" },
  { id: 108, english: "to listen", hanzi: "听", pinyin: "tīng" },
  { id: 109, english: "classmate", hanzi: "同学", pinyin: "tóng xué" },
  { id: 110, english: "hello (on phone)", hanzi: "喂", pinyin: "wèi" },
  { id: 111, english: "I / me", hanzi: "我", pinyin: "wǒ" },
  { id: 112, english: "we / us", hanzi: "我们", pinyin: "wǒ men" },
  { id: 113, english: "five", hanzi: "五", pinyin: "wǔ" },
  { id: 114, english: "to like", hanzi: "喜欢", pinyin: "xǐ huan" },
  { id: 115, english: "under; below", hanzi: "下", pinyin: "xià" },
  { id: 116, english: "afternoon", hanzi: "下午", pinyin: "xià wǔ" },
  { id: 117, english: "to rain", hanzi: "下雨", pinyin: "xià yǔ" },
  { id: 118, english: "Mr.; sir", hanzi: "先生", pinyin: "xiān sheng" },
  { id: 119, english: "now", hanzi: "现在", pinyin: "xiàn zài" },
  { id: 120, english: "to think; want", hanzi: "想", pinyin: "xiǎng" },
  { id: 121, english: "small", hanzi: "小", pinyin: "xiǎo" },
  { id: 122, english: "Miss; young lady", hanzi: "小姐", pinyin: "xiǎo jie" },
  { id: 123, english: "some", hanzi: "些", pinyin: "xiē" },
  { id: 124, english: "to write", hanzi: "写", pinyin: "xiě" },
  { id: 125, english: "thank you", hanzi: "谢谢", pinyin: "xiè xie" },
  { id: 126, english: "week", hanzi: "星期", pinyin: "xīng qī" },
  { id: 127, english: "student", hanzi: "学生", pinyin: "xué sheng" },
  { id: 128, english: "to study", hanzi: "学习", pinyin: "xué xí" },
  { id: 129, english: "school", hanzi: "学校", pinyin: "xué xiào" },
  { id: 130, english: "one", hanzi: "一", pinyin: "yī" },
  { id: 131, english: "a little bit", hanzi: "一点儿", pinyin: "yī diǎn er" },
  { id: 132, english: "doctor", hanzi: "医生", pinyin: "yī shēng" },
  { id: 133, english: "hospital", hanzi: "医院", pinyin: "yī yuàn" },
  { id: 134, english: "clothes", hanzi: "衣服", pinyin: "yī fu" },
  { id: 135, english: "chair", hanzi: "椅子", pinyin: "yǐ zi" },
  { id: 136, english: "to have", hanzi: "有", pinyin: "yǒu" },
  { id: 137, english: "month", hanzi: "月", pinyin: "yuè" },
  { id: 138, english: "goodbye", hanzi: "再见", pinyin: "zài jiàn" },
  { id: 139, english: "at; in", hanzi: "在", pinyin: "zài" },
  { id: 140, english: "how", hanzi: "怎么", pinyin: "zěn me" },
  { id: 141, english: "how about", hanzi: "怎么样", pinyin: "zěn me yàng" },
  { id: 142, english: "this", hanzi: "这", pinyin: "zhè" },
  { id: 143, english: "China", hanzi: "中国", pinyin: "zhōng guó" },
  { id: 144, english: "noon", hanzi: "中午", pinyin: "zhōng wǔ" },
  { id: 145, english: "to live", hanzi: "住", pinyin: "zhù" },
  { id: 146, english: "table", hanzi: "桌子", pinyin: "zhuō zi" },
  { id: 147, english: "character", hanzi: "字", pinyin: "zì" },
  { id: 148, english: "yesterday", hanzi: "昨天", pinyin: "zuó tiān" },
  { id: 149, english: "to do", hanzi: "做", pinyin: "zuò" },
  { id: 150, english: "to sit", hanzi: "坐", pinyin: "zuò" },
];
