export const HSK1 = [
  { id: 1, english: "I / me", hanzi: "我", pinyin: "wǒ", known: false },
  { id: 2, english: "you", hanzi: "你", pinyin: "nǐ", known: false },
  { id: 3, english: "he / him", hanzi: "他", pinyin: "tā", known: false },
  { id: 4, english: "she / her", hanzi: "她", pinyin: "tā", known: false },
  { id: 5, english: "we / us", hanzi: "我们", pinyin: "wǒmen", known: false },
  {
    id: 6,
    english: "you (plural)",
    hanzi: "你们",
    pinyin: "nǐmen",
    known: false,
  },
  {
    id: 7,
    english: "they / them",
    hanzi: "他们",
    pinyin: "tāmen",
    known: false,
  },
  { id: 8, english: "this", hanzi: "这", pinyin: "zhè", known: false },
  { id: 9, english: "that", hanzi: "那", pinyin: "nà", known: false },
  { id: 10, english: "who", hanzi: "谁", pinyin: "shéi", known: false },
  { id: 11, english: "what", hanzi: "什么", pinyin: "shénme", known: false },
  { id: 12, english: "where", hanzi: "哪儿", pinyin: "nǎr", known: false },
  {
    id: 13,
    english: "why",
    hanzi: "为什么",
    pinyin: "wèishénme",
    known: false,
  },
  { id: 14, english: "how", hanzi: "怎么", pinyin: "zěnme", known: false },
  {
    id: 15,
    english: "how many / how much",
    hanzi: "多少",
    pinyin: "duōshǎo",
    known: false,
  },
  {
    id: 16,
    english: "a little / few",
    hanzi: "一点儿",
    pinyin: "yìdiǎnr",
    known: false,
  },
  { id: 17, english: "big", hanzi: "大", pinyin: "dà", known: false },
  { id: 18, english: "small", hanzi: "小", pinyin: "xiǎo", known: false },
  { id: 19, english: "good", hanzi: "好", pinyin: "hǎo", known: false },
  { id: 20, english: "bad", hanzi: "不好", pinyin: "bù hǎo", known: false },
  { id: 21, english: "many / a lot", hanzi: "多", pinyin: "duō", known: false },
  { id: 22, english: "few", hanzi: "少", pinyin: "shǎo", known: false },
  {
    id: 23,
    english: "to be (is/are)",
    hanzi: "是",
    pinyin: "shì",
    known: false,
  },
  { id: 24, english: "to have", hanzi: "有", pinyin: "yǒu", known: false },
  {
    id: 25,
    english: "to not have",
    hanzi: "没有",
    pinyin: "méiyǒu",
    known: false,
  },
  { id: 26, english: "to do / make", hanzi: "做", pinyin: "zuò", known: false },
  { id: 27, english: "to go", hanzi: "去", pinyin: "qù", known: false },
  { id: 28, english: "to come", hanzi: "来", pinyin: "lái", known: false },
  {
    id: 29,
    english: "to see / look at",
    hanzi: "看",
    pinyin: "kàn",
    known: false,
  },
  { id: 30, english: "to eat", hanzi: "吃", pinyin: "chī", known: false },
  { id: 31, english: "to drink", hanzi: "喝", pinyin: "hē", known: false },
  {
    id: 32,
    english: "to speak / talk",
    hanzi: "说",
    pinyin: "shuō",
    known: false,
  },
  { id: 33, english: "to listen", hanzi: "听", pinyin: "tīng", known: false },
  {
    id: 34,
    english: "to sleep",
    hanzi: "睡觉",
    pinyin: "shuìjiào",
    known: false,
  },
  { id: 35, english: "to buy", hanzi: "买", pinyin: "mǎi", known: false },
  { id: 36, english: "to like", hanzi: "喜欢", pinyin: "xǐhuan", known: false },
  { id: 37, english: "to want", hanzi: "要", pinyin: "yào", known: false },
  { id: 38, english: "to give", hanzi: "给", pinyin: "gěi", known: false },
  { id: 39, english: "to learn", hanzi: "学习", pinyin: "xuéxí", known: false },
  { id: 40, english: "to write", hanzi: "写", pinyin: "xiě", known: false },
  { id: 41, english: "to ask", hanzi: "问", pinyin: "wèn", known: false },
  { id: 42, english: "please", hanzi: "请", pinyin: "qǐng", known: false },
  {
    id: 43,
    english: "thank you",
    hanzi: "谢谢",
    pinyin: "xièxie",
    known: false,
  },
  {
    id: 44,
    english: "sorry",
    hanzi: "对不起",
    pinyin: "duìbuqǐ",
    known: false,
  },
  {
    id: 45,
    english: "no problem",
    hanzi: "没关系",
    pinyin: "méiguānxi",
    known: false,
  },
  { id: 46, english: "teacher", hanzi: "老师", pinyin: "lǎoshī", known: false },
  {
    id: 47,
    english: "student",
    hanzi: "学生",
    pinyin: "xuésheng",
    known: false,
  },
  { id: 48, english: "friend", hanzi: "朋友", pinyin: "péngyou", known: false },
  { id: 49, english: "water", hanzi: "水", pinyin: "shuǐ", known: false },
  { id: 50, english: "food / meal", hanzi: "饭", pinyin: "fàn", known: false },
  { id: 51, english: "tea", hanzi: "茶", pinyin: "chá", known: false },
  { id: 52, english: "fruit", hanzi: "水果", pinyin: "shuǐguǒ", known: false },
  { id: 53, english: "apple", hanzi: "苹果", pinyin: "píngguǒ", known: false },
  {
    id: 54,
    english: "goodbye",
    hanzi: "再见",
    pinyin: "zàijiàn",
    known: false,
  },
  {
    id: 55,
    english: "to work",
    hanzi: "工作",
    pinyin: "gōngzuò",
    known: false,
  },
  {
    id: 56,
    english: "to study (in school)",
    hanzi: "上学",
    pinyin: "shàngxué",
    known: false,
  },
  { id: 57, english: "to read", hanzi: "读书", pinyin: "dúshū", known: false },
  { id: 58, english: "happy", hanzi: "高兴", pinyin: "gāoxìng", known: false },
  { id: 59, english: "to sit", hanzi: "坐", pinyin: "zuò", known: false },
  { id: 60, english: "to stand", hanzi: "站", pinyin: "zhàn", known: false },
  { id: 61, english: "to walk", hanzi: "走", pinyin: "zǒu", known: false },
  { id: 62, english: "how old", hanzi: "多大", pinyin: "duōdà", known: false },
  { id: 63, english: "to open", hanzi: "开", pinyin: "kāi", known: false },
  { id: 64, english: "to close", hanzi: "关", pinyin: "guān", known: false },
  { id: 65, english: "to arrive", hanzi: "到", pinyin: "dào", known: false },
  {
    id: 66,
    english: "to go out",
    hanzi: "出去",
    pinyin: "chūqù",
    known: false,
  },
  { id: 67, english: "to enter", hanzi: "进", pinyin: "jìn", known: false },
  { id: 68, english: "to return", hanzi: "回", pinyin: "huí", known: false },
  {
    id: 69,
    english: "to start",
    hanzi: "开始",
    pinyin: "kāishǐ",
    known: false,
  },
  { id: 70, english: "to play", hanzi: "玩", pinyin: "wán", known: false },
  { id: 71, english: "to sit", hanzi: "坐", pinyin: "zuò", known: false },
  { id: 72, english: "to stand", hanzi: "站", pinyin: "zhàn", known: false },
  { id: 73, english: "to walk", hanzi: "走", pinyin: "zǒu", known: false },
  { id: 74, english: "to know", hanzi: "知道", pinyin: "zhīdào", known: false },
  {
    id: 75,
    english: "to call (on phone)",
    hanzi: "打电话",
    pinyin: "dǎ diànhuà",
    known: false,
  },
  {
    id: 76,
    english: "to help",
    hanzi: "帮助",
    pinyin: "bāngzhù",
    known: false,
  },
  { id: 77, english: "to rest", hanzi: "休息", pinyin: "xiūxi", known: false },
  {
    id: 78,
    english: "to work",
    hanzi: "工作",
    pinyin: "gōngzuò",
    known: false,
  },
  { id: 79, english: "to wait", hanzi: "等", pinyin: "děng", known: false },
  {
    id: 80,
    english: "to see / meet",
    hanzi: "见",
    pinyin: "jiàn",
    known: false,
  },
  {
    id: 81,
    english: "to talk",
    hanzi: "聊天",
    pinyin: "liáotiān",
    known: false,
  },
  {
    id: 82,
    english: "to call (name)",
    hanzi: "叫",
    pinyin: "jiào",
    known: false,
  },
  { id: 83, english: "to study", hanzi: "读", pinyin: "dú", known: false },
  { id: 84, english: "to teach", hanzi: "教", pinyin: "jiāo", known: false },
  { id: 85, english: "to live", hanzi: "住", pinyin: "zhù", known: false },
  { id: 86, english: "to ask", hanzi: "问", pinyin: "wèn", known: false },
  {
    id: 87,
    english: "to understand",
    hanzi: "懂",
    pinyin: "dǒng",
    known: false,
  },
  { id: 88, english: "to think", hanzi: "想", pinyin: "xiǎng", known: false },
  {
    id: 89,
    english: "to know (someone)",
    hanzi: "认识",
    pinyin: "rènshi",
    known: false,
  },
  { id: 90, english: "to leave", hanzi: "离开", pinyin: "líkāi", known: false },
  { id: 91, english: "weather", hanzi: "天气", pinyin: "tiānqì", known: false },
  {
    id: 92,
    english: "hot (temperature)",
    hanzi: "热",
    pinyin: "rè",
    known: false,
  },
  { id: 93, english: "cold", hanzi: "冷", pinyin: "lěng", known: false },
  { id: 94, english: "sunny", hanzi: "晴", pinyin: "qíng", known: false },
  { id: 95, english: "rain", hanzi: "雨", pinyin: "yǔ", known: false },
  { id: 96, english: "snow", hanzi: "雪", pinyin: "xuě", known: false },
  {
    id: 97,
    english: "to like / love",
    hanzi: "爱",
    pinyin: "ài",
    known: false,
  },
  { id: 98, english: "family", hanzi: "家", pinyin: "jiā", known: false },
  { id: 99, english: "child", hanzi: "孩子", pinyin: "háizi", known: false },
  { id: 100, english: "son", hanzi: "儿子", pinyin: "érzi", known: false },
  {
    id: 101,
    english: "daughter",
    hanzi: "女儿",
    pinyin: "nǚ'ér",
    known: false,
  },
  { id: 102, english: "dad", hanzi: "爸爸", pinyin: "bàba", known: false },
  { id: 103, english: "mom", hanzi: "妈妈", pinyin: "māma", known: false },
  {
    id: 104,
    english: "older brother",
    hanzi: "哥哥",
    pinyin: "gēge",
    known: false,
  },
  {
    id: 105,
    english: "younger brother",
    hanzi: "弟弟",
    pinyin: "dìdi",
    known: false,
  },
  {
    id: 106,
    english: "older sister",
    hanzi: "姐姐",
    pinyin: "jiějie",
    known: false,
  },
  {
    id: 107,
    english: "younger sister",
    hanzi: "妹妹",
    pinyin: "mèimei",
    known: false,
  },
  {
    id: 108,
    english: "classmate",
    hanzi: "同学",
    pinyin: "tóngxué",
    known: false,
  },
  {
    id: 109,
    english: "hospital",
    hanzi: "医院",
    pinyin: "yīyuàn",
    known: false,
  },
  {
    id: 110,
    english: "school",
    hanzi: "学校",
    pinyin: "xuéxiào",
    known: false,
  },
  {
    id: 111,
    english: "store",
    hanzi: "商店",
    pinyin: "shāngdiàn",
    known: false,
  },
  {
    id: 112,
    english: "restaurant",
    hanzi: "饭馆",
    pinyin: "fànguǎn",
    known: false,
  },
  { id: 113, english: "hotel", hanzi: "酒店", pinyin: "jiǔdiàn", known: false },
  {
    id: 114,
    english: "China",
    hanzi: "中国",
    pinyin: "Zhōngguó",
    known: false,
  },
  {
    id: 115,
    english: "Beijing",
    hanzi: "北京",
    pinyin: "Běijīng",
    known: false,
  },
  { id: 116, english: "car", hanzi: "车", pinyin: "chē", known: false },
  { id: 117, english: "plane", hanzi: "飞机", pinyin: "fēijī", known: false },
  {
    id: 118,
    english: "bus",
    hanzi: "公共汽车",
    pinyin: "gōnggòng qìchē",
    known: false,
  },
  { id: 119, english: "train", hanzi: "火车", pinyin: "huǒchē", known: false },
  {
    id: 120,
    english: "bike",
    hanzi: "自行车",
    pinyin: "zìxíngchē",
    known: false,
  },
  {
    id: 121,
    english: "teacher",
    hanzi: "老师",
    pinyin: "lǎoshī",
    known: false,
  },
  {
    id: 122,
    english: "doctor",
    hanzi: "医生",
    pinyin: "yīshēng",
    known: false,
  },
  {
    id: 123,
    english: "Monday",
    hanzi: "星期一",
    pinyin: "xīngqī yī",
    known: false,
  },
  {
    id: 124,
    english: "Tuesday",
    hanzi: "星期二",
    pinyin: "xīngqī èr",
    known: false,
  },
  {
    id: 125,
    english: "Wednesday",
    hanzi: "星期三",
    pinyin: "xīngqī sān",
    known: false,
  },
  {
    id: 126,
    english: "Thursday",
    hanzi: "星期四",
    pinyin: "xīngqī sì",
    known: false,
  },
  {
    id: 127,
    english: "Friday",
    hanzi: "星期五",
    pinyin: "xīngqī wǔ",
    known: false,
  },
  {
    id: 128,
    english: "Saturday",
    hanzi: "星期六",
    pinyin: "xīngqī liù",
    known: false,
  },
  {
    id: 129,
    english: "Sunday",
    hanzi: "星期天",
    pinyin: "xīngqī tiān",
    known: false,
  },
  { id: 130, english: "today", hanzi: "今天", pinyin: "jīntiān", known: false },
  {
    id: 131,
    english: "yesterday",
    hanzi: "昨天",
    pinyin: "zuótiān",
    known: false,
  },
  {
    id: 132,
    english: "tomorrow",
    hanzi: "明天",
    pinyin: "míngtiān",
    known: false,
  },
  { id: 133, english: "year", hanzi: "年", pinyin: "nián", known: false },
  { id: 134, english: "month", hanzi: "月", pinyin: "yuè", known: false },
  { id: 135, english: "day", hanzi: "日", pinyin: "rì", known: false },
  { id: 136, english: "time", hanzi: "时间", pinyin: "shíjiān", known: false },
  { id: 137, english: "now", hanzi: "现在", pinyin: "xiànzài", known: false },
  {
    id: 138,
    english: "morning",
    hanzi: "早上",
    pinyin: "zǎoshang",
    known: false,
  },
  {
    id: 139,
    english: "afternoon",
    hanzi: "下午",
    pinyin: "xiàwǔ",
    known: false,
  },
  {
    id: 140,
    english: "evening",
    hanzi: "晚上",
    pinyin: "wǎnshang",
    known: false,
  },
  { id: 141, english: "number", hanzi: "号码", pinyin: "hàomǎ", known: false },
  { id: 142, english: "book", hanzi: "书", pinyin: "shū", known: false },
  { id: 143, english: "pen", hanzi: "笔", pinyin: "bǐ", known: false },
  { id: 144, english: "money", hanzi: "钱", pinyin: "qián", known: false },
  { id: 145, english: "clothes", hanzi: "衣服", pinyin: "yīfu", known: false },
  { id: 146, english: "table", hanzi: "桌子", pinyin: "zhuōzi", known: false },
  { id: 147, english: "chair", hanzi: "椅子", pinyin: "yǐzi", known: false },
  { id: 148, english: "cat", hanzi: "猫", pinyin: "māo", known: false },
  { id: 149, english: "dog", hanzi: "狗", pinyin: "gǒu", known: false },
  {
    id: 150,
    english: "to know (how to)",
    hanzi: "会",
    pinyin: "huì",
    known: false,
  },
];
